### ISSUE TITLE
using early return 

### ISSUE THREAD

**Issue by AlfaBravoX** [empicano/aiomqtt#223]
This is probably not a bug, but I would like to use early return within  ```async for message in messages:```  loop

ie.

```
async for message in messages:
  try:
      if message.topic.matches("not-interesting-topic/#"):
          print(f"early return")
          return
      elif message.topic.matches("interesting-topic/#"):
         do something
      ...
```

return used in first condition obviously breaks listening process and no more messages are received if return is applied. Is there a change to exit listening loop for only one message and continue receiving messages?

I am able to rewrite the code to completely avoid returns but I prefer to keep using it.

**Comment by AlfaBravoX** [comment]
for anyone meeting this scenario, using ```continue``` fixes this issue

**Comment by AlfaBravoX** [comment]
I just realised,  when I need to exit mqtt_message block without any action and wait for next message,  it is not possible.  

if i use Return,  no  more messages are received as i exit the listening loop.

if i use continue,  then the code after continue is still executed. 

any idea how to just exit the particular message match and wait for next one?

**Comment by empicano** [comment]
> if i use continue, then the code after continue is still executed

That should not be the case. Could you post a minimal self-contained example that shows the problem together with the output you would expect/like to have?

**Comment by AlfaBravoX** [comment]
Sure this is the code I am currently using, I just removed some unnecessary parts:

```
async def mqtt_message():
    async with mqtt_aioclient.messages() as messages:
        await mqtt_aioclient.subscribe(
            [
                (MYTOPIC,0)
            ]
        )
        async for message in messages:
            if message.topic.matches(MYTOPIC):
                for _zwave_node in _zwave_nodes:
                    if json_object["nodeId"] == _zwave_node['zwaveNode']['nodeId']:
                        print("do something here and exit this topic match")
                        continue #!! I need here the block is exited 

                print("this to be execute only if above condition in for loop is False!")
                print("but it is execute always")
```

**Comment by AlfaBravoX** [comment]
I think I found the culprit. The issue is that the ```continue``` just makes to exit the ```for``` loop. If loop is omitted,  the continue works as expected and exits the topic matches.

**Comment by empicano** [comment]
You got it 👍 In your example, the `continue` skips the current element of the `_zwave_nodes` for loop, not the current element of the `Client.messages` for loop.

If you want to stick with a `continue`, you can rewrite it to something like this (using [`any`](https://docs.python.org/3/library/functions.html#any)):

```python
async def mqtt_message():
    async with mqtt_aioclient.messages() as messages:
        await mqtt_aioclient.subscribe(
            [
                (MYTOPIC,0)
            ]
        )
        async for message in messages:
            if message.topic.matches(MYTOPIC):
                if any([
                    json_object["nodeId"] == _zwave_node['zwaveNode']['nodeId']
                    for _zwave_node
                    in _zwave_nodes
                ]):
                    print("do something here and exit this topic match")
                    continue
```

But that's formatting, the important part is that it does what it should 😋

**Comment by AlfaBravoX** [comment]
awesome, all is clear now. thanks for confirming my theory 

and even more elegant option for my use case would be:

```python
for _zwave_node in _zwave_nodes:
    if json_object["nodeId"] == _zwave_node['zwaveNode']['nodeId']:
        print("do something here with json data and exit the LOOP")
        break
    else:
        print("iteration did not find nodeId , lets do something else and finish Client.messages loop ")
```

no ```continue```  needed ;-)

**Comment by AlfaBravoX** [comment]
All resolved, thanks again @empicano  !
