### ISSUE TITLE
Operation Timed out

### ISSUE THREAD

**Issue by daffa-d** [empicano/aiomqtt#336]
i still get operation timed out. i have added some code for issue on windows users, and i still get operation timed out

my code like this : 
```
import asyncio
import aiomqtt
from aiomqtt import ProtocolVersion
import pymodbus.client as ModbusClient
from pymodbus import (
    ExceptionResponse,
    FramerType,
    ModbusException,
    pymodbus_apply_logging_config,
)
import sys
import os
import random

async def modbus_pressure():
    interval_connect = 5
    client = ModbusClient.ModbusSerialClient(
        port="COM11",
        baudrate=9600,
        retries=4
    )
    client.connect()

    clientMqtt = aiomqtt.Client(hostname='***.emqxsl.com',
                                 port=8883, 
                                 username='***',
                                 password='***',
                                 protocol=ProtocolVersion.V5,
                                 identifier='pressure551')

    while True:
        result = client.read_holding_registers(0, 1, 3)
        result = result.registers[0] / 100
        pressure = 12 * ((result - 0.5) / (4.5 - 0.5))
        print(f"Pressure: {pressure}")
        try:
            async with clientMqtt:
                await clientMqtt.publish('pressure', f'{pressure}', qos=2)
                print(f"Published: {pressure}")
        except aiomqtt.MqttError as e:
            print(f"Error {e}, Reconnecting...{interval_connect} Seconds")
            await asyncio.sleep(interval_connect)

if __name__ == "__main__":
    if sys.platform.lower() == "win32" or os.name.lower() == "nt":
        from asyncio import set_event_loop_policy, WindowsSelectorEventLoopPolicy
        set_event_loop_policy(WindowsSelectorEventLoopPolicy())
    asyncio.run(modbus_pressure())
```

and the output like this

![image](https://github.com/user-attachments/assets/186bcb24-2939-43f5-843f-6bb4c6505ba5)

any idea ?

**Comment by empicano** [comment]
Did you try to run your code with a localhost broker or with `test.mosquitto.org`? You can also try to increase the `timeout` parameter and see if that changes things. The default timeout is 10 seconds.

**Comment by daffa-d** [comment]
I'm using EMQX, I have an account on the platform, but when I want to connect it keeps timeout.I've also tried changing the timeout but it's the same.

**Comment by empicano** [comment]
Can you try to run your code with a localhost broker and with `test.mosquitto.org`?

I strongly suspect that the client can't build a connection to the broker for some reason. Let's rule out any other problems before diving deeper.

**Comment by daffa-d** [comment]
Okay, I checked my connection with Broker, it looks good. but, I'll double check what the cause is

**Comment by daffa-d** [comment]
case closed. because the problem is encrypted in broker. so my device can't connect with broker. i just little setting in broker and my device it's working. Thanks @empicano

**Comment by empicano** [comment]
Great, thanks for reporting back! 👍
